### ISSUE TITLE
Provide Weightage to HTTPOnly Cookie

### ISSUE THREAD

**Issue by maruthi-adithya** [snift/snift-extension#11]
HttpOnly is a flag added to cookies that tell the browser not to display the cookie through client-side scripts. The idea behind HttpOnly is not to spill out cookies when an XSS flaw exists, as a hacker might be able to run their script but the fundamental benefit of having an XSS vulnerability is lost.

**Comment by shrirambalaji** [comment]
HTTPOnly flags added to cookies, cannot be accessed / verified through JS and Browser APIs. So this is not possible to implement.
