### ISSUE TITLE
When the Tab is Switched, there is an API call to the server.

### ISSUE THREAD

**Issue by maruthi-adithya** [snift/snift-extension#4]
Refer to the GIF attached.
![bug](https://user-images.githubusercontent.com/25739266/56845870-3c4d2900-68e5-11e9-8e17-48240fbcf1f6.gif)

**Comment by shrirambalaji** [comment]
@maruthi-adithya Did you get a chance to confirm if this still occurs in latest develop?

**Comment by maruthi-adithya** [comment]
Fixed in Latest Develop.
