### ISSUE TITLE
Some APIs need not have the Favicon. Need a Symbol to represent that

### ISSUE THREAD

**Issue by maruthi-adithya** [snift/snift-extension#5]
Ref Screenshot Attached
![image](https://user-images.githubusercontent.com/25739266/56845928-2b50e780-68e6-11e9-9b7e-c1151cd14c2d.png)

**Comment by shrirambalaji** [comment]
@maruthi-adithya Can you elaborate on what you have on mind for the symbol. An example or an icon link itself helps.
